name: Test PHP Framework

on:
  push:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del codice
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        coverage: xdebug
        tools: composer:v2

    - name: Ottieni la cache delle dipendenze di Composer
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Installa le dipendenze di Composer
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Install Google Chrome and Chromedriver (for Chrome 115+)
      run: |
        # Installa Google Chrome Stable
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

        # Recupera la versione di Chrome Stable installata
        CHROME_VERSION=$(google-chrome-stable --version | grep -oP '\d+\.\d+\.\d+' | head -n 1)
        echo "Detected Chrome Stable version: $CHROME_VERSION"

        # Trova la versione di Chromedriver compatibile tramite l'API di Chrome for Testing
        # La versione di Chromedriver per Stable è l'ultima versione disponibile per quella major release di Chrome
        CHROMEDRIVER_MAJOR_VERSION=$(echo $CHROME_VERSION | cut -d'.' -f1)
        CHROMEDRIVER_URL=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json" | \
                           jq -r ".versions[] | select(.version | startswith(\"$CHROMEDRIVER_MAJOR_VERSION.\")) | .downloads.chromedriver[] | select(.platform == \"linux64\") | .url")

        if [ -z "$CHROMEDRIVER_URL" ]; then
          echo "Error: Could not find Chromedriver URL for Chrome version $CHROME_VERSION"
          exit 1
        fi

        echo "Downloading Chromedriver from: $CHROMEDRIVER_URL"
        wget -q "$CHROMEDRIVER_URL" -O chromedriver.zip
        unzip -o chromedriver.zip -d chromedriver_temp
        sudo mv chromedriver_temp/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver
        rm -rf chromedriver.zip chromedriver_temp
      env:
        # Assicurati che jq sia disponibile per parsing JSON
        DEBIAN_FRONTEND: noninteractive # Per evitare domande durante apt-get install

    - name: Start Chromedriver
      run: |
        chromedriver --url-base=/wd/hub & # Avvia Chromedriver in background
        sleep 5 # Dai tempo a Chromedriver di avviarsi

    - name: Start PHP built-in web server
      run: |
        php -S 127.0.0.1:8000 -t public/ > /dev/null 2>&1 & # Avvia il server in background
        echo "PHP web server started on 127.0.0.1:8000"
      # Assicurati che 'public/' sia la root del tuo server web

    - name: Wait for web server to be ready
      run: |
        timeout 60 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' 127.0.0.1:8000)" != "200" ]]; do sleep 1; done'

    - name: Esegui i test di Codeception
      run: _src/_sh/_codeception.run.sh
